name: 'Call REST API when a file is pushed'

on:
  push:
    paths:
      - '*.txt' # match '*.txt' files (created or updated)
    branches: [ test ] # match specific branch

jobs:
  prepare-files:
    runs-on: ubuntu-latest
    outputs:
      matrix-added: ${{ steps.file-changes.outputs.files_added }}
      matrix-modified: ${{ steps.file-changes.outputs.files_modified }}
    steps:
      - id: file-changes
        uses: trilom/file-changes-action@v1.2.4

  post-files-added:
    needs: prepare-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJSON(needs.prepare-files.outputs.matrix-added) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo file
        run: |
          echo ${{ matrix.file }} # to test if the correct file was passed

      - name: Get Bearer Toker
        uses: fjogeleit/http-request-action@v1.16.4
        id: bearer
        with:
          url: 'https://login.cloud.camunda.io/oauth/token'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
          data: '{"grant_type": "client_credentials", "audience": "value_2", "client_id":"", "client_secret": ""}'
